#### q. 1 How to find the memory size of any array

In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.size*a.itemsize)

24


#### q.2 create an array of (3,5,8 )

In [3]:
a=np.ones((3,5,8),dtype=int)
print(a)

[[[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]]


### q.3 
#### a) Create a null vector of size 10 but the fifth value which is 1 
#### b)Reverse a vector (first element becomes last)
### c) sort it.

In [4]:
a=np.zeros(10,)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
a=np.arange(7)
print(a)
fir=a[0]
a[0]=a[6]
a[6]=a[0]
a[6]=fir
print(a)


[0 1 2 3 4 5 6]
[6 1 2 3 4 5 0]


In [27]:
a=np.array([[17,5,-2],[6,2,8]])
print(np.sort(a))

[[-2  5 17]
 [ 2  6  8]]


#### q.4 Create an array as :
[[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]]

note : don not use np.array direct.



In [36]:
a=np.ones((1,5,5),dtype=int)
print(a)
a[0][1][1:4]=0
a[0][2][1:4:2]=0
a[0][2][2]=9
a[0][3][1:4]=0
print(a)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[[1 1 1 1 1]
  [1 0 0 0 1]
  [1 0 9 0 1]
  [1 0 0 0 1]
  [1 1 1 1 1]]]


#### q.5 Create a 3x3 matrix with values ranging from 0 to 8 

In [41]:
a=np.mat(np.arange(9).reshape(3,3))
a

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### q.6 Find indices of non-zero elements from [1,2,0,0,4,0] 

In [89]:
a=np.array([1,2,0,0,4,0])
np.where(a>0)

(array([0, 1, 4], dtype=int64),)

#### Q.7 Create a 10x10 array with random values and find the minimum and maximum values 

In [49]:
a=np.random.uniform(0,200,100).reshape(10,10)
print(a)

[[  5.82986357  74.5785768   19.17466294  39.39286407 188.48412248
   74.25423433 145.80016036  25.23202173  50.25658434 176.24705942]
 [180.6592301   57.52705164 193.4226263  133.61986713 100.60135471
   75.60048173  67.47365886 190.40214102 138.66676572 106.82034001]
 [  8.69793959  49.51017512 188.63414453 111.37203325  71.50364647
    1.89007483  50.70965344  50.84533803  34.13710521  68.99599194]
 [ 40.52981027  12.58030804  19.59207918  99.34550046  13.93211808
  187.03071267  41.21952703  92.84246999  82.93365142  58.26754369]
 [ 64.70570296  42.31951668  56.05365755  23.42100714 137.85037496
  128.90523787  62.30588067 176.05979123  77.27514502 122.21786006]
 [104.63386524  65.01136072 185.95808461 169.6402818  168.2245896
  190.85772731   0.49648525  98.42382005 187.58262381  26.88535196]
 [ 48.99882768 101.01238412 135.68430196  66.55199152  61.27293432
  155.15958224   6.57078765 157.1595725   85.70805629 125.80189143]
 [141.10060498  19.69372588 180.76923297 164.46249372  7

In [50]:
a.min()

0.4964852536192943

In [51]:
a.max()

193.42262630245926

#### q.8 Create a random vector of size 30 and find the mean value

In [65]:
a=np.random.randint(0,50,30)
print(a)
print(np.mean(a))

[39 16  1 39 49  6 44 25 35 46 49 38 37 14 34  1  6 11 26 16 42 23 17 37
 16 28 30 20 26 32]
26.766666666666666


##### q.9 Create a 2dimensional array of  size with 1 on the border and 0 inside 

In [71]:
a=np.ones((5,5),dtype=int)
print(a)
a[1:4,1:4]=0
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### q.10 How to add a border (filled with 0's) around an existing array? 

In [80]:
a=np.zeros((7,7),dtype=int)
print(a)
a[1:6,1:6]=2
print(a)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 2 2 2 2 2 0]
 [0 2 2 2 2 2 0]
 [0 2 2 2 2 2 0]
 [0 2 2 2 2 2 0]
 [0 2 2 2 2 2 0]
 [0 0 0 0 0 0 0]]


#### q.11 Create a 5x5 matrix with values 1,2,3,4 just below the main diagonal 

In [1]:
import numpy as np
m1=np.diag([1,2,3,4],k=-1)
print(m1)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### q.12 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [2]:
k1=np.ones((5,3))
k11=np.mat(k1)
type(k11)
k2=np.ones((3,2))
k22=np.mat(k2)
k11*k22

matrix([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])

#### q.13  create a 1D array, square all  elements which are greater than 3 

In [6]:
a=np.random.randint(1,15,5)
print(a)
k=np.where(a>3,a**2,a)
k

[1 6 7 2 1]


array([ 1, 36, 49,  2,  1])

#### q.14 Extract the integer part of a random array of positive numbers using  different methods 


In [3]:
a=np.random.uniform(1,100,10)
a

array([85.46813626, 73.6479549 , 90.13130419,  7.32238932, 26.40550507,
       15.79086451, 72.16867115, 44.61450269, 61.97300236, 19.24488065])

In [4]:
np.floor(a)
a1=a.astype("int")
a1

array([85, 73, 90,  7, 26, 15, 72, 44, 61, 19])

#### q.15 Create a 5x5 matrix with row values ranging from 0 to 4


In [5]:
import numpy as np
import numpy as np
x = np.zeros((5,5))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(5)   # broadcasting 
print(x)



Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### q.16 Create a vector of size 10 with values ranging from 0 to 1, both excluded 


In [6]:
import numpy as np
a=np.linspace(0.1,1,10)
print(a)


[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#### q.17 Create random vector of size 10 and replace the maximum value by 0 (★★☆)





In [7]:
import numpy as np
a=np.random.rand(11)
print("the array is :\n",a,"\n")
print("the max element is ",np.max(a), "at index number ",np.argmax(a))
a[np.argmax(a)]=0
print("the array is replaced with 0 at index",np.argmax(a),"with new value\n ",a)

the array is :
 [0.56338713 0.92148909 0.76617127 0.72534864 0.16497253 0.12206926
 0.39076952 0.79605461 0.20304849 0.62048816 0.40746647] 

the max element is  0.9214890949777844 at index number  1
the array is replaced with 0 at index 7 with new value
  [0.56338713 0.         0.76617127 0.72534864 0.16497253 0.12206926
 0.39076952 0.79605461 0.20304849 0.62048816 0.40746647]


or python cor questions 

### q. 1  u need to lower all the characters in the given string   s = "A man, A plan, A goodman:" and remove all non-alphanumeric characters from the string and check after removing if the string is palindrome or not.


In [8]:
s="A man, A plan, A goodman:"
s1=s.replace(" ","")
print(s1)
s1=s1.replace(",","").replace(":","")
print(s1)
l_s=s1.lower()
if l_s==l_s[::-1]:
    print("palindorme")
else:
    print("not")

Aman,Aplan,Agoodman:
AmanAplanAgoodman
not


## q. 2
## Take a list containg only strings. Now, take a string input from user and rearrange the elements of the list according to the number of occurence of the string taken from user in the elements of the list.


E.g.-LIST : ["no bun","bug bun bug bun bug bug","bunny bug","buggy bug bug buggy"]
STRING TAKEN : "bug"


OUTPUT LIST:["bug bun bug bun bug bug","buggy bug bug buggy","bunny bug","no bun"]


In [9]:
l=["no bun","bug bun bug bun bug bug","bunny bug","buggy bug bug buggy"]
d={}
for i in l:
    v=i.count("bug")
    d[i]=v
print(d)
print(d.items())
k=sorted(d.items(),key=lambda t:t[1],reverse=True)
print(k)
l1=[]
for i in k:
    l1.append(i[0])
print(l1)
    

{'no bun': 0, 'bug bun bug bun bug bug': 4, 'bunny bug': 1, 'buggy bug bug buggy': 4}
dict_items([('no bun', 0), ('bug bun bug bun bug bug', 4), ('bunny bug', 1), ('buggy bug bug buggy', 4)])
[('bug bun bug bun bug bug', 4), ('buggy bug bug buggy', 4), ('bunny bug', 1), ('no bun', 0)]
['bug bun bug bun bug bug', 'buggy bug bug buggy', 'bunny bug', 'no bun']
