In [7]:
d=[400,300,100,200]
sp=[40,50,70,60]
#t=d/sp
for i in d:
    for j in sp:
        t=i/j
    print(t)


6.666666666666667
5.0
1.6666666666666667
3.3333333333333335


In [8]:
d=[400,300,100,200]
sp=[40,50,70,60]
#t=d/sp
t=list(zip(d,sp))
t

[(400, 40), (300, 50), (100, 70), (200, 60)]

In [10]:
main=[]
for i in t:
    l=[]
    for j in i:
        l.append(j)
    main.append(l)
main

[[400, 40], [300, 50], [100, 70], [200, 60]]

In [13]:
time=[]
for k in main:
    time.append(k[0]/k[1])
print(time)
        

[10.0, 6.0, 1.4285714285714286, 3.3333333333333335]


## above code is too long, if data is large then list won't fullfill the purpose
### use array(solves efficiently) in numpy

# numpy

### array performs element wise operation

In [14]:
import numpy as np
d1=np.array([400,300,100,200])
sp1=np.array([40,50,70,60])
d1/sp1


array([10.        ,  6.        ,  1.42857143,  3.33333333])

### array stores homogeneous data
### only no.s(int,float,complex)--stores string but not same ops
### fast and efficient
### supports various mathematical fns

### array can perform complex operations

## the core data structure of numpy is : ndarray -n dimensional array

## u can create array from list and tuple

In [15]:
a=np.array([1,2,3,4,5,6]) ## array creation from 1-dlist 
a

array([1, 2, 3, 4, 5, 6])

In [16]:
type(a)

numpy.ndarray

In [18]:
a.dtype ## 1byte=8bites #it is taking 32 bites or 4 bytes in memory allocation

dtype('int32')

In [19]:
a=np.array([1,2.45,3.33,4,5,6])
a.dtype  #dtype tells us the data type of element

dtype('float64')

### 2-d list

In [20]:
a2=np.array([[20,30,70,90],[100,200,300]])     ## array creation from 2-d list
a2

C:\Users\rupan\AppData\Local\Temp\ipykernel_2532\3046475815.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2=np.array([[20,30,70,90],[100,200,300]])     ## array creation from 2-d list


array([list([20, 30, 70, 90]), list([100, 200, 300])], dtype=object)

### always give equal no of elements in the lists

In [21]:
a2=np.array([[20,30,70,90],[100,200,300,400]])     ## array creation from 2-d list
a2

array([[ 20,  30,  70,  90],
       [100, 200, 300, 400]])

## 3-d array

In [24]:
a3=np.array([[[2,3],[50,80]],[[20,30],[90,100]]])
a3   # 3-d is collection of 2-d

array([[[  2,   3],
        [ 50,  80]],

       [[ 20,  30],
        [ 90, 100]]])

## creating array using tuple()

In [25]:
a1=np.array((20,30,50))
a1

array([20, 30, 50])

In [28]:
a1=np.array("hello")
a1
a1.dtype   ## oth-d array--single value

dtype('<U5')

## important properties/attributes of ndarray

# 1.ndim-to check the no of dimension/axis of an array

### 3-d is collection of 2-d

In [31]:
print(np.array([20,30,90]))
a1=np.array([20,30,90])
a1.ndim   #this array has 1 dimension

[20 30 90]


1

In [32]:
a2=np.array([[20,30,70,90],[100,200,300,400]])
a2.ndim

2

In [33]:
c=np.array([[1, 2, 3], [4, 5, 6]])
c.ndim

2

In [34]:
c=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
c.ndim   ## dim -how many square brackets are open

3

In [36]:
e=np.array([[[[[2,4,5,6,90]]]]])
e.ndim  ## 5 brackets are open so 5 dimension

5

In [37]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5]) # in  single dimension we can not judge the rows and columns
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e=np.array([[[[1, 2, 3], [4, 5, 6]]]])
f=np.array([[2,3,4,5]])
g=np.array([[[[[20,30]]]]])
print(a.ndim)
print(np.ndim(a))
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)
print(g.ndim)




0
0
1
2
3
4
2
5


In [42]:
a1=np.array([1,2,3],ndmin=5)
a1

array([[[[[1, 2, 3]]]]])

## 2.shape- shape can be defined as the number of elements present in each dimension

In [43]:
a=np.array([1,2,3])
print(a.shape)

(3,)


## shape of 1-d- you can not judge in 1d if its a row or a column thats why comma is given after 3

## shape of 2-d

In [45]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1.shape

(2, 3)

In [46]:
arr2=np.array([[2,3,4,5],[3,4,5,6],[4,56,6,7]])
arr2.shape

(3, 4)

In [47]:
arr4=np.array([[1,2,3,4]])
arr4.shape

(1, 4)

In [48]:
arr5=np.array([[[1,2],[3,4]]])
print(arr5.shape)

(1, 2, 2)


In [49]:
k=np.array([[[[[[[2,3,4],[45,78,90],[50,90,89]]]]]]])
print(k.shape)



(1, 1, 1, 1, 1, 3, 3)


In [50]:
a=np.array([[[[[[[["pizza","sweetcorn","noodles","burger"]]]]]]]])
a.shape

(1, 1, 1, 1, 1, 1, 1, 4)

# 25/10/22

In [7]:
import numpy as np

In [13]:
a1=np.array([[[2,3],[4,5],[6,7],[8,9]],[[10,11],[12,13],[14,15],[16,17]]])
a1.shape

(2, 4, 2)

In [10]:
a1=np.array([[[[30,66,70],[23,66,22],[33,55,66]]]])
a1

array([[[[30, 66, 70],
         [23, 66, 22],
         [33, 55, 66]]]])

In [11]:
a1.shape

(1, 1, 3, 3)

In [15]:
#create an array of 1,1,3,3,3
a=np.array([[[[[2,3,4],[1,2,3],[2,3,4]],[[3,4,5],[2,3,4],[2,4,5]],[[3,4,5],[4,5,6],[5,7,8]]]]])
a.shape

(1, 1, 3, 3, 3)

In [19]:
a.ndim

5

# rank and dimensions are same

# size of array : returns the no of elements across the axis

In [22]:
a1=np.array([20,40,70,90])
print(np.size(a1))
print(np.size(a1,axis=0))

4
4


In [25]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(np.size(a)) #means 8 no of elements are present
print(np.size(a,0))
print(np.size(a,1))

8
2
4


In [28]:
#3d-array
a=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(np.size(a))
print(np.size(a,axis=0))
print(np.size(a,axis=1))
print(np.size(a,axis=2))

16
2
2
4


In [29]:
print(np.size(a,axis=3)) #tere is no third axis

IndexError: tuple index out of range

# 4. ITEMSIZE-represents memory occupied by each element in bytes

## dtype-tells datatype of element

In [32]:
l=[1,2,3]
a=np.array(l)
print(a.dtype) ## int32 means 4 bytes 4*8bits=32bits
print(a.itemsize) ##itemsize tells how much memory a particular element is taking
print(a.size*a.itemsize) ##total memory occupied by AN ARRAY

int32
4
12


In [33]:
print(a.size*a.itemsize) ##total memory occupied by AN ARRAY

12


## DType-by default float

In [35]:
a=np.ones((2,3))   ##ones is element and shape is (2,3)
print(a)
a.dtype   ## by default: float

[[1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [36]:
a=np.ones((2,3,1))
print(a)

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


# 6. astype: convert the existing dtype to another dtype

In [37]:
a1=a.astype("int")   #float to int
a1

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]])

# List vs Array

### 1.element wise operation on array and we cannot perform that on list
### 2. arrays are faster 3. array takes less memory 4. data stored in contigious memory 

In [39]:
## proof of above statement
import sys
l=list(range(100))hb 
a=np.arange(100)
print(sys.getsizeof(l))
print(a.itemsize)
print("list takes :",sys.getsizeof(l)*len(l),"bytes")  ##ys.getsizeof(l) : size of each element in the list
print("array takes : ",a.itemsize*a.size,"bytes" ) ## itemsize: size of each element in the array.



856
4
list takes : 85600 bytes
array takes :  400 bytes


## array indexing and slicing: in 1-d array

In [45]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[-1])
print(arr[2:])
print(arr[1:5:3])

1
4
[3 4]
[2]


## indexing and slicing in 2-d array

In [50]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])
print(a[0]) #means first row,total 3 rows
print(a[-1])
print(a[-1][2])
print(a[-1][3:])


[2 3 4 5 6]
[20 30 40 50 90]
40
[50 90]


In [54]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])
print(a[:,1])


[ 3  8 30]


In [55]:
print(a[:,1:5:3])

[[ 3  6]
 [ 8 90]
 [30 90]]


In [56]:
print(a[0:3:2,0:4:3])

[[ 2  5]
 [20 50]]


In [58]:
print(a[0:3:2,0:5])

[[ 2  3  4  5  6]
 [20 30 40 50 90]]


In [59]:
print(a[0:3:2,:])

[[ 2  3  4  5  6]
 [20 30 40 50 90]]


In [60]:
print(a[1:3,1:3])

[[ 8  9]
 [30 40]]


In [61]:

a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])  # 2d array  here , 
print(a)
print(a[0]) #or print(a[-3]) means first row
print(a[1]) #or print(a[-2]) means second row
print(a[2]) #or print(a[-1]) means third row
print(a[-1]) # or print(a[2])  means  last row
print(a[0][2]) # fetch 4
print(a[1][2:]) # 9,0,90
print(a[-2][0])  # fetch 7
print(a[:,2])  ## all rows with 2nd column  (discontinous manner)
print(a[0:2,2:]) ## ist and 2nd rows with columns from 2nd(disconinous manner)
print(a[1,2:3])
print(a[0:3:2,2:5:2]) ## feth 4,6 40 ,90
#print(a[[0,2],[1,3]])
print(a[0:3:2,1:4:2]) ## fetch 3, 30 5 and 50
 


[[ 2  3  4  5  6]
 [ 7  8  9  0 90]
 [20 30 40 50 90]]
[2 3 4 5 6]
[ 7  8  9  0 90]
[20 30 40 50 90]
[20 30 40 50 90]
4
[ 9  0 90]
7
[ 4  9 40]
[[ 4  5  6]
 [ 9  0 90]]
[9]
[[ 4  6]
 [40 90]]
[[ 3  5]
 [30 50]]


In [63]:
a=np.array([[[[[[[["pizza","sweet corn","coffee","lemonade"]]]]]]]])
print(a[0][0][0][0][0][0][0])
print(a[0][0][0][0][0][0][0][1])


['pizza' 'sweet corn' 'coffee' 'lemonade']
sweet corn


In [64]:
print(a[0][0][0][0][0][0][0][1:])

['sweet corn' 'coffee' 'lemonade']


In [68]:
a=np.array([[[[[1,2,3,50,],[4,5,6,90],[7,8,9,99],[11,12,3,98]]]]])
print(a[0][0][0][-1][-1])
print(a[0][0][0][3][-1])
print(a[0][0][0][0][2:])

98
98
[ 3 50]


In [75]:
a=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])
print(a[0][0][-1][-2])

19


In [73]:
print(a[0][0][2][2::2])

[13 15]


In [74]:
print(a[0][0][2][2:5:2])

[13 15]


In [87]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1][0])


[7 8 9]


In [86]:
print(arr[1][:,1:3])

[[ 8  9]
 [11 12]]


In [93]:
print(arr[1][1][1:3])

[11 12]


# indexing with boolean: from EDA point of view

In [2]:
import numpy as np
a=np.array([[20,30,60],[40,80,90],[70,90,100]])
a

array([[ 20,  30,  60],
       [ 40,  80,  90],
       [ 70,  90, 100]])

In [8]:
a[a<40]  ##masking phenomenon

array([20, 30])

In [9]:
x=a<40
x          #OR

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [10]:
a[x]

array([20, 30])

In [11]:
np.where(a<40,85,"nothing")   ##to find index 

array([['85', '85', 'nothing'],
       ['nothing', 'nothing', 'nothing'],
       ['nothing', 'nothing', 'nothing']], dtype='<U11')

## double/multiple condition

In [13]:
(a%2==0)&(a>40)  ##return in boolean

array([[False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [12]:
a[(a%2==0)&(a>40)] ##doing masking

array([ 60,  80,  90,  70,  90, 100])

In [3]:
a=[[[[2,3,4,5],[40,50,60,90]]]]
a=np.array(a)
print(a[0][0][:,1])


[ 3 50]


In [3]:
import numpy as np
a=[
    [
        [
            [2,3,4,5],[40,50,60,90]
        ]
    ]
]
a=np.array(a)
print(a[0][0][[0,1],[0,0]])  ##to fetch 2 40

[ 2 40]


In [30]:
a[0][0][1,2:]

array([60, 90])

In [33]:
a[0][0][[0,1],[1,3]]  #oth row and 1st row for fetching 3 and 90 and it's for axis and after that gives indexing for condition and put in []

array([ 3, 90])

In [35]:
a[0][0][[0,1],[2,0]]

array([ 4, 40])

In [38]:
a[0][0][[0,1],[0,3]]

array([ 2, 90])

# iterations

In [40]:
a=np.array([1,2,3,4])
for i in a:
    print(i)

1
2
3
4


### np.nditer use this instead of n dim nested loops

In [41]:
a=np.array([[2,3,4],[7,8,9]])
print(a)
for i in np.nditer(a):
    print(i)

[[2 3 4]
 [7 8 9]]
2
3
4
7
8
9


# copy and view`

## the main differene is that the copy is a new array while view  is just a view of original array

In [43]:
a=np.array([2,3,4,5])
a1=a.copy() ## deep copy
a1[3]=70
print("copy----",a1)
print("original array--",a) # deep copy or copy does not show any changes in original array

copy---- [ 2  3  4 70]
original array-- [2 3 4 5]


In [44]:
a=np.array([2,3,4,5])
a1=a.view() ## shallow copy
a1[3]=70
print("copy----",a1)
print("original array--",a)  ## view(shallow copy) also show changes in original array

copy---- [ 2  3  4 70]
original array-- [ 2  3  4 70]


In [45]:
a2=a   #implicit changes or it's viewing this in view
a2[2]="700"  ##implicitely view
print(a2)
print(a)

[  2   3 700  70]
[  2   3 700  70]


In [47]:
a=np.array([1,2,3])
a2=a.copy()
a2[2]="700"
print(a2)
print(a)

[  1   2 700]
[1 2 3]


# shape manipulation: reshape and resize

### reshape behaves like deep copy while resize behaves like shallow copy

In [48]:
x=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(x.shape)

(2, 6)


### how we represents (2,6) as (6,2),(3,4),(4,3),(12,1),(1,12)

In [49]:
x1=x.reshape(1,12)
print("deep copy--",x1)
print("original---",x)

deep copy-- [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
original--- [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [50]:
x1=x.reshape(12,1)
print("deep copy--",x1)
print("original---",x)

deep copy-- [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
original--- [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [51]:
x1=x.reshape(3,4)
print("deep copy--",x1)
print("original---",x)

deep copy-- [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
original--- [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [52]:
x1=x.reshape(4,3)
print("deep copy--",x1)
print("original---",x)

deep copy-- [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
original--- [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [53]:
x1=x.reshape(6,2)
print("deep copy--",x1)
print("original---",x)

deep copy-- [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
original--- [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# resize-changes in original and in copy returns none

In [54]:
x1=x.resize(1,12)
print("deep copy--",x1)
print("original---",x)

deep copy-- None
original--- [[ 1  2  3  4  5  6  7  8  9 10 11 12]]


## can we reshape into any shape?
## as long as elements are same we can reshape into any shape otherwise not

In [58]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
newarr=arr.reshape(2,2,-1)
newarr1=arr.reshape(2,-1,2)
newarr2=arr.reshape(-1,2,2)
print(newarr)
print(newarr1)
print(newarr2)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays: converting a multidimensional array into a 1D array

## nd array to 1-d array
1.reshape
2. flatten-treates as deep copy
3.ravel-shallow copy

In [60]:
arr=np.array([[1,2,3],[4,5,6]])  ##2-D
arr1=arr.ravel()
print("1-D---",arr1)
print("2-D---",arr)

1-D--- [1 2 3 4 5 6]
2-D--- [[1 2 3]
 [4 5 6]]


In [61]:
arr1[3]=700
print("ravel shalow copy--",arr1)
print("original--",arr)

ravel shalow copy-- [  1   2   3 700   5   6]
original-- [[  1   2   3]
 [700   5   6]]


## will not use if we do not need any changes in original copy

In [62]:
arr=np.array([[1,2,3],[4,5,6]])  ##2-D
arr1=arr.flatten()
print("1-D---",arr1)
print("2-D---",arr)

1-D--- [1 2 3 4 5 6]
2-D--- [[1 2 3]
 [4 5 6]]


In [64]:
arr1[3]=700
print("flatten deep copy--",arr1)
print("original--",arr)  ##no changes in original copy using flatten

flatten deep copy-- [  1   2   3 700   5   6]
original-- [[1 2 3]
 [4 5 6]]


In [65]:
arr=np.array([[1,2,3],[4,5,6]])  ##2-D
arr1=arr.reshape(-1)
print("1-D---",arr1)
print("2-D---",arr)

1-D--- [1 2 3 4 5 6]
2-D--- [[1 2 3]
 [4 5 6]]


# arange()-generates the sequence of array

# we use range() to create sequence of list

In [67]:
a=np.arange(1,11)
print(a)
a1=np.arange(1,11,2)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [4]:
a2=np.arange()

TypeError: arange() requires stop to be specified.

# linspace(start,end,number): return evenly spaced numbers over a specified interval and no is total no of elemnts

In [68]:
a=np.arange(-30,30,10)
a

array([-30, -20, -10,   0,  10,  20])

In [69]:
a=np.linspace(-30,30,10)  #calculate stepsize itself
a

array([-30.        , -23.33333333, -16.66666667, -10.        ,
        -3.33333333,   3.33333333,  10.        ,  16.66666667,
        23.33333333,  30.        ])

# logspace()

In [72]:
a=np.logspace(-30,30,10) #generates logvalue of corresponding element of linspace
a

array([1.00000000e-30, 4.64158883e-24, 2.15443469e-17, 1.00000000e-10,
       4.64158883e-04, 2.15443469e+03, 1.00000000e+10, 4.64158883e+16,
       2.15443469e+23, 1.00000000e+30])

# 27/10/22

In [4]:
import numpy as np
a=[[[[2,3,4,5],[40,50,60,90]]]]
a=np.array(a)
print(a[0][0][[0,1],[1,2]])

[ 3 60]


In [6]:
import numpy as np

In [7]:
a=np.arange(3,30,2)
print(a)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [8]:
a[[5,6,9,-1]]  ##fancy indexing/advance indexing

array([13, 15, 21, 29])

### some arrays are used for initialization purpose


### 1. np.empty() 2.np.zeros() 3. np.ones()

In [7]:
import numpy as np
a=np.empty([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
a=np.empty([1,3],dtype="int")
a

array([[0, 0, 0]])

In [10]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr=np.zeros((3,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## numpy operations

## taking two arrays a1 and a2 as below:

In [14]:
a1=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,0]])
a1

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [15]:
a2=np.array([[3,20,5,4],[3,4,50,6],[7,8,7,0]])
a2

array([[ 3, 20,  5,  4],
       [ 3,  4, 50,  6],
       [ 7,  8,  7,  0]])

In [16]:
a1+a2

array([[ 4, 22,  8,  8],
       [ 6,  8, 55, 12],
       [14, 16, 16,  0]])

In [17]:
a1-a2

array([[ -2, -18,  -2,   0],
       [  0,   0, -45,   0],
       [  0,   0,   2,   0]])

In [18]:
a1*a2

array([[  3,  40,  15,  16],
       [  9,  16, 250,  36],
       [ 49,  64,  63,   0]])

In [21]:
a1/a2

C:\Users\rupan\AppData\Local\Temp\ipykernel_28484\3705041958.py:1: RuntimeWarning: invalid value encountered in true_divide
  a1/a2


array([[0.33333333, 0.1       , 0.6       , 1.        ],
       [1.        , 1.        , 0.1       , 1.        ],
       [1.        , 1.        , 1.28571429,        nan]])

In [22]:
a1*3

array([[ 3,  6,  9, 12],
       [ 9, 12, 15, 18],
       [21, 24, 27,  0]])

In [23]:
a1<a2

array([[ True,  True,  True, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [24]:
a1>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [25]:
a1<2

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [26]:
a1

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [27]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 0.        ]])

In [28]:
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849,  0.        ]])

In [29]:
np.cos(a1)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [-0.9899925 , -0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026,  1.        ]])

In [30]:
a1=np.array([20.4,-2.8,9.3])
np.ceil(a1)

array([21., -2., 10.])

### floor gives <= to value
### while ceil gives >= to value

In [31]:
import math 
a=3
math.floor(a)
math.ceil(a)

3

In [32]:
round(0.8167222,2)

0.82

In [33]:
np.floor(a1)

array([20., -3.,  9.])

In [34]:
a1=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,0]])
a1

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [35]:
np.max(a1)

9

In [37]:
np.min(a1)

0

In [38]:
np.argmax(a1)  ##gives index value of max element

10

In [39]:
a1.max(axis=0)  ##row-wise output

array([7, 8, 9, 6])

In [40]:
a1.max(axis=1)

array([4, 6, 9])

In [41]:
a1.sum() ## sum of whole array

52

In [42]:
a1.sum(axis=0)  ##axis-wise sum

array([11, 14, 17, 10])

# sort()

In [43]:
np.sort(a1,axis=0)  #elements are sorting row wise

array([[1, 2, 3, 0],
       [3, 4, 5, 4],
       [7, 8, 9, 6]])

In [44]:
np.sort(a1,axis=1)

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [0, 7, 8, 9]])

# matrix()

In [45]:
a=np.mat([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [46]:
a=np.mat([[1,2,3],[3,4,7],[1,2,3]])
a

matrix([[1, 2, 3],
        [3, 4, 7],
        [1, 2, 3]])

In [47]:
a=np.mat([[[1,2,3],[3,4,7],[1,2,3]]])  # extra dimension is not possible in matrix(only2-d) that's why error
a

ValueError: matrix must be 2-dimensional

In [48]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

## Diff b/w array and matrix
## at most 2 dimension for matrix while array can be n dimension
## in matrix operations are performed row and col wise while in array they are performed element wise
## matrix is a subclass of array


In [50]:
m1=np.mat([[1,2],[3,4]])
m2=np.mat([[3,4],[8,9]])
m1*m2  ## dot


matrix([[19, 22],
        [41, 48]])

In [51]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[3,4],[8,9]])
m1*m2 
## difference in mat and array

array([[ 3,  8],
       [24, 36]])

## Transpose()

In [52]:
a=np.array([[1,2],[3,4]])

In [53]:
a.T  ##property of array

array([[1, 3],
       [2, 4]])

In [54]:
np.transpose(a)  ##function of numpy

array([[1, 3],
       [2, 4]])

## np.trace()-gives sum of diagonal elemnts

In [55]:
np.trace(a)

5

## inverse()

In [56]:
a=np.array([[1,2],[3,4]])  
d=np.matrix([[1,2],[3,4]])
print(a.shape)
print(d.shape)
np.linalg.inv(d)



(2, 2)
(2, 2)


matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

## Broadcasting

## when shapes are different,we use this

In [57]:
### it refers to the ability of numpy to treat arrays of different shapes during arithmetic operations. arithmetic operations are usually done 

In [58]:
## case1: when shape is same : same as normal element wise operations
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)
print(a1,"\n\n")


print(a2)
a1+a2

[[0 1 2 3]
 [4 5 6 7]] 


[[ 8  9 10 11]
 [12 13 14 15]]


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [59]:
## case2: a.) when shapes are different
a1=np.arange(9).reshape(3,3) ##2-d
print(a1)
a1*2  ##scalar

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [60]:
## case2: b.) when shapes are different
a1=np.arange(9).reshape(3,3)
a2=np.arange(3).reshape(1,3)
print(a1,"\n\n")

print(a2)

a1+a2

[[0 1 2]
 [3 4 5]
 [6 7 8]] 


[[0 1 2]]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

# 31/10/22

## create an array of (3,2,3)

In [1]:
import numpy as np
a=np.ones((3,2,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## create a vector of size 10,vector means 1-d

In [2]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# create an array with random values of (3,3)

## random module():numpy functions

In [5]:
np.random.random()

0.2646703690962272

## random.random()-value will be in range(0,1)

## to fix random value use seed()

In [12]:
np.random.seed(2)
np.random.random()

0.43599490214200376

## random value between the specified range use uniform()

In [15]:
np.random.uniform(10,30)

18.706447852365535

In [19]:
np.random.seed(2)
np.random.uniform(10,30)

18.719898042840075

## by default float data type in numpy

## generate random values of certain range i.e. array with in given range

In [21]:
np.random.uniform(1,100,10)  ## shape is 1-d and 10 elements 

array([53.38506733, 14.32341459, 51.84423401, 19.2595467 , 78.74817963,
       85.54355397, 49.9294469 , 84.80958705,  8.88490222, 51.01936292])

In [25]:
np.random.seed(2)   ## elements are fixed
np.random.uniform(1,100,10).reshape(2,5)

array([[44.16349531,  3.56669695, 55.41658531, 44.09691687, 42.61641241],
       [33.70314728, 21.26021477, 62.30782567, 30.66581269, 27.41590024]])

In [23]:
np.random.uniform(1,100,10).reshape(10,1)

array([[20.9725794 ],
       [64.4002658 ],
       [48.82391372],
       [51.01843528],
       [39.30237246],
       [79.57010799],
       [58.42041371],
       [17.06756125],
       [70.37448231],
       [96.49055693]])

In [26]:
np.random.uniform(1,100,10).reshape(2,8)

ValueError: cannot reshape array of size 10 into shape (2,8)

## for int type random value use randint()

In [27]:
np.random.randint(1,10)   

5

In [28]:
np.random.randint(1,10,6)   

array([7, 4, 3, 1, 5, 3])

In [30]:
np.random.randint(1,10,8).reshape(4,2)   

array([[7, 9],
       [6, 4],
       [1, 1],
       [3, 9]])

In [32]:
np.random.seed(3)
np.random.randint(1,10,7)

array([9, 4, 9, 9, 1, 6, 4])

In [34]:
np.random.seed(3)
np.random.randint(1,10,7).reshape(1,7,1)   ##3-d

array([[[9],
        [4],
        [9],
        [9],
        [1],
        [6],
        [4]]])

## normal distribution-mean,median,mode are approximately equal

In [36]:
a2=np.random.normal(loc=5,scale=7,size=9) #local is mean and scale is standard deviation-variation of data point from mean
a2

array([ 7.78520102, -6.404102  ,  0.52745132,  1.07433091, 17.73287812,
        6.096008  , -3.42293336,  0.07158417, 12.1345431 ])

In [39]:
print(np.mean(a2),np.median(a2))

3.954995698547812 1.07433091230843


In [40]:
a2=np.random.normal(loc=10,scale=4,size=1000)
a2

array([ 7.86147936,  4.69244417, 12.67220966, 11.14351122,  8.51729894,
       14.20180448, 11.04525001,  7.22161092,  1.90123223, 13.38381262,
        8.10178697,  4.4169378 ,  3.06886216,  9.06710308,  8.52605334,
        2.74733559, 11.01814216, 14.25579614,  6.04155128,  6.13979566,
        4.31318909,  9.12401651, 10.2693548 ,  4.26898942,  9.86110156,
        6.50715458, 15.56152459,  6.30929341, 13.36287628, 14.34226979,
        6.05632663, 15.90242478,  5.16771617, 15.07317091,  2.71531526,
       13.0442146 ,  7.20978474,  9.65092994, 12.98165294,  5.80470628,
       15.21548957, 13.50457043, 19.83340531,  7.46581602,  8.25793488,
        8.49369545,  4.67093512, 10.90946179, 10.47993955, 11.19475328,
       17.28520116, 11.44239649, 11.10506151,  9.38855391, 12.00506347,
       13.00505973, 14.90924992,  9.71643937, 13.20888425, 14.89865857,
       10.91716421, 12.84054688, 13.27234474,  1.69851139,  7.82958   ,
        7.8599468 , 13.54146191, 12.80483479,  6.51125008, 10.37

In [43]:
print(np.mean(a2),np.median(a2))

10.111929426537518 10.086643195385543


In [45]:
import statistics
statistics.mode(a2)   ## numpy does not have mode function

7.861479355541965

## skewness in normal dist is because of outliers

## standard normal distribution- A normal distribution whose mean is approximately equal to 0 and s.d is approximately equal to 1.

## randn()

In [48]:
a=np.random.randn(3,4,2)
a

array([[[ 0.58605233, -0.67352455],
        [-0.47984536,  1.17480089],
        [ 0.25497935, -0.74473132],
        [ 0.93153923, -0.41375187]],

       [[ 0.05880358, -0.73188932],
        [ 0.0707861 ,  0.38862078],
        [ 0.71137067,  0.36241479],
        [ 1.09069785, -0.6271943 ]],

       [[-0.5459815 , -1.63535723],
        [-0.0192706 ,  0.36350072],
        [-1.44457002,  0.3957821 ],
        [-0.49427409,  0.36191427]]])

In [49]:
print(np.mean(a))

-0.044130312385165765


In [54]:
a1=np.random.randn(1000)
a1

array([-1.03393839e+00,  2.67557907e-01,  6.74336445e-01,  1.72623533e-01,
       -3.98322985e-01, -4.31569312e-01,  2.66374293e-01,  5.03999582e-01,
        1.44528780e+00,  8.37703556e-01, -1.95508565e+00,  2.18715859e-01,
       -1.17347414e+00,  4.75743918e-01,  2.55861012e-01, -7.12488671e-02,
       -4.29472749e-01,  4.33183082e-01,  2.72616391e-01, -1.20182651e-01,
        1.04891431e+00,  2.13135066e+00, -6.13173808e-01, -2.24446270e-01,
       -1.83461559e+00, -1.16950573e+00,  8.68813658e-01, -4.05606465e-02,
       -8.04125497e-01, -1.09206856e+00, -1.29601530e-01,  3.01835042e-01,
       -9.72771351e-01, -8.80954690e-01,  2.01317820e+00, -4.96855179e-01,
       -8.29151042e-01, -3.32996799e-01, -2.68230586e+00, -1.28236669e+00,
        3.60879471e-01,  3.12899979e-01,  1.23676476e+00, -1.37134086e-01,
        4.25754757e-01,  1.48361869e+00,  7.40155062e-01,  2.15131435e+00,
       -1.43716752e-01,  1.37595019e+00,  2.40249779e+00, -6.03555167e-01,
       -7.66205496e-01, -

In [58]:
print(np.mean(a1),np.std(a1))  ##standard normal dist

-0.02524078317793115 1.0078931438151801


In [57]:
print(np.median(a1))

-0.034766134429356874


In [60]:
## generate random sample of size 4*7 between 0 to 1
np.random.random_sample((4,7))

array([[0.68788591, 0.46551928, 0.62777815, 0.12127442, 0.19793028,
        0.12305502, 0.0463631 ],
       [0.72697621, 0.02708083, 0.28067244, 0.91285346, 0.97181203,
        0.2306639 , 0.11880483],
       [0.30090518, 0.87460867, 0.43719497, 0.54190896, 0.04567423,
        0.24878775, 0.13089305],
       [0.79171067, 0.88692091, 0.59228673, 0.18658482, 0.87029362,
        0.1733087 , 0.49887722]])

## create an identity matrix:eye()

In [63]:
a=np.eye(3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [64]:
a=np.eye(3,k=1,dtype=int)
a

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [65]:
a=np.eye(3,k=2,dtype=int)
a

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [66]:
a=np.eye(3,k=-1,dtype=int)
a

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [67]:
a=np.eye(3,k=-2,dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 0]])

## to extract diagonal array-np.diag()

In [75]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("diagonal elements are",np.diag(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements are [1 5 9]


In [74]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("diagonal elements are",np.diag(a,k=1))   ## upper diagonal elements

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements are [2 6]


In [76]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("diagonal elements are",np.diag(a,k=2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements are [3]


In [77]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("diagonal elements are",np.diag(a,k=-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements are [4 8]


In [78]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("diagonal elements are",np.diag(a,k=-2)) ##2-d

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements are [7]


In [79]:
diag_ele=np.diag(a)
print(diag_ele)
print(np.diag(diag_ele))

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [80]:
## diagflat: for creating diagonal array means the element is to be placed diagonally based on the value of k
a1=np.diagflat([1,2,3,4,5],k=0)
print(a1)
a2=np.diagflat([5,6,7,8,9],k=-1)
print(a2)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[0 0 0 0 0 0]
 [5 0 0 0 0 0]
 [0 6 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 8 0 0]
 [0 0 0 0 9 0]]


# tri, triu, tril

In [81]:
a=[[1,2,3],[4,5,6],[7,8,9]]
u_array=np.triu(a,k=0)
print(u_array)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [82]:
u_array=np.triu(a,k=1)
print(u_array)

[[0 2 3]
 [0 0 6]
 [0 0 0]]


In [83]:
u_array=np.triu(a,k=2)
print(u_array)

[[0 0 3]
 [0 0 0]
 [0 0 0]]


# fromfunction()-create the array based on the functionality you specify and gives index

In [84]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [85]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])